package csu.coderwu.csuhelp.db.dao;

import csu.coderwu.csuhelp.db.entity.WxMiniUser;
import csu.coderwu.csuhelp.db.entity.WxMiniUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WxMiniUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=WxMiniUserSqlProvider.class, method="countByExample")
    long countByExample(WxMiniUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @DeleteProvider(type=WxMiniUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(WxMiniUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from wx_mini_user",
        "where open_id = #{openId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into wx_mini_user (open_id, nickname, gender, ",
        "city, province, ",
        "country, avatar_url, ",
        "union_id)",
        "values (#{openId,jdbcType=VARCHAR}, #{nickname,jdbcType=VARCHAR}, #{gender,jdbcType=INTEGER}, ",
        "#{city,jdbcType=VARCHAR}, #{province,jdbcType=VARCHAR}, ",
        "#{country,jdbcType=VARCHAR}, #{avatarUrl,jdbcType=VARCHAR}, ",
        "#{unionId,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="openId", before=false, resultType=String.class)
    int insert(WxMiniUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=WxMiniUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="openId", before=false, resultType=String.class)
    int insertSelective(WxMiniUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMiniUser selectOneByExample(WxMiniUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMiniUser selectOneByExampleSelective(@Param("example") WxMiniUserExample example, @Param("selective") WxMiniUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxMiniUser> selectByExampleSelective(@Param("example") WxMiniUserExample example, @Param("selective") WxMiniUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=WxMiniUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatar_url", property="avatarUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="union_id", property="unionId", jdbcType=JdbcType.VARCHAR)
    })
    List<WxMiniUser> selectByExample(WxMiniUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMiniUser selectByPrimaryKeySelective(@Param("openId") String openId, @Param("selective") WxMiniUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "open_id, nickname, gender, city, province, country, avatar_url, union_id",
        "from wx_mini_user",
        "where open_id = #{openId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatar_url", property="avatarUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="union_id", property="unionId", jdbcType=JdbcType.VARCHAR)
    })
    WxMiniUser selectByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WxMiniUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WxMiniUser record, @Param("example") WxMiniUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WxMiniUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WxMiniUser record, @Param("example") WxMiniUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WxMiniUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WxMiniUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mini_user
     *
     * @mbg.generated
     */
    @Update({
        "update wx_mini_user",
        "set nickname = #{nickname,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=INTEGER},",
          "city = #{city,jdbcType=VARCHAR},",
          "province = #{province,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "avatar_url = #{avatarUrl,jdbcType=VARCHAR},",
          "union_id = #{unionId,jdbcType=VARCHAR}",
        "where open_id = #{openId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WxMiniUser record);
}