server:
  port: 8888

spring:
  profiles:
    active: dev

logging:
  level:
    csu.coderwu.csuhelp.wx.mini: debug

wechat:
   mini:
      appid: 111
      secret: 111
      token: 111
      aesKey: 111
      msgDataFormat: JSON


